# ============================================================
# keypair.tf — Emergency-SSH key pair (ED25519)
#
# Primary instance access is SSM Session Manager (no open ports, full
# audit trail). This key pair exists ONLY for break-glass SSH when SSM
# is unavailable, and port 22 stays closed unless ssh_allowed_cidrs is
# set (security_groups.tf).
#
# The private key is generated by Terraform and stored ONLY in AWS
# Secrets Manager — it never touches the repo or local disk. It DOES
# live in the Terraform state; HCP Terraform encrypts state at rest and
# scopes access to the workspace team, which is the accepted trade-off.
#
# Retrieve it (requires secretsmanager:GetSecretValue):
#   aws secretsmanager get-secret-value \
#     --secret-id <name_prefix>-ssh-private-key \
#     --query SecretString --output text > key.pem && chmod 600 key.pem
# ============================================================

resource "tls_private_key" "ssh" {
  algorithm = "ED25519"
}

resource "aws_key_pair" "web" {
  key_name   = "${local.name_prefix}-key"
  public_key = tls_private_key.ssh.public_key_openssh

  tags = {
    Name = "${local.name_prefix}-key"
  }
}

resource "aws_secretsmanager_secret" "ssh_private_key" {
  name        = "${local.name_prefix}-ssh-private-key"
  description = "Emergency SSH private key for ${local.name_prefix}-ec2. Break-glass only — use SSM Session Manager for routine access."

  # Allow re-creation within the recovery window during rebuilds.
  recovery_window_in_days = 7

  tags = {
    Name = "${local.name_prefix}-ssh-private-key"
  }
}

resource "aws_secretsmanager_secret_version" "ssh_private_key" {
  secret_id     = aws_secretsmanager_secret.ssh_private_key.id
  secret_string = tls_private_key.ssh.private_key_openssh
}
