name: Deploy Website
description: Deploy the community day website to EC2 instance

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::511489843375:role/EC2SSM
        aws-region: af-south-1

    - name: Create zip file
      run: |
        cd src
        zip -r ../hennie-francis-tech.zip .

    - name: Upload to S3
      run: |
        aws s3 cp hennie-francis-tech.zip s3://temp-deploy-hennie-francis-tech-bucket/hennie-francis-tech.zip

  deploy-to-ec2:
    needs: build-and-upload
    runs-on: ubuntu-latest
    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::511489843375:role/EC2SSM
        aws-region: af-south-1

    - name: Deploy to EC2
      run: |
        aws ssm send-command \
          --instance-ids "i-02723168e2145a4f2" \
          --document-name "AWS-RunShellScript" \
          --parameters '{
            "commands": [
              "cd /usr/share/nginx/html",
              "aws s3 cp s3://temp-deploy-hennie-francis-tech-bucket/hennie-francis-tech.zip .",
              "unzip -o hennie-francis-tech.zip -d hennie-francis-tech",
              "rm hennie-francis-tech.zip",
              "chown -R nginx:nginx hennie-francis-tech"
            ]
          }'

  restart-nginx:
      needs: deploy-to-ec2
      runs-on: ubuntu-latest
      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::511489843375:role/EC2SSM
          aws-region: af-south-1

      - name: Restart Nginx
        run: |
          aws ssm send-command \
            --instance-ids "i-02723168e2145a4f2" \
            --document-name "AWS-RunShellScript" \
            --parameters '{
              "commands": [
                "systemctl restart nginx",
                "systemctl status nginx"
              ]
            }'